name: 'Cool workflow'
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: echo "Tests passed"
      - name: Get the package version
        id: package-version
        run: echo "::set-output name=current-version::$(node -p "require('./package.json').version")"
        env: 
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          tag: ${{ steps.package-version.outputs.current-version }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Version v$tag til :ios: og :android: er tilgængelig nu internt i Development & Production appen (<https://play.google.com/apps/internaltest/4699592015152166842/|Intern test prod> :android:, <https://play.google.com/apps/internaltest/4700745607886572208/|Intern test dev> :android: og i TestFlight :ios:)"}' $SLACK_WEBHOOK_URL